### ISSUE TITLE
Fix the oopsy error when you double edit a to-do item without refreshing the page

### ISSUE THREAD

**Issue by JatinBehlCarrot** [shreyasachdeva123/to-do-list#12]
![image](https://user-images.githubusercontent.com/71669969/117866810-90759c80-b265-11eb-973c-d52fd17804d9.png)

How to reproduce:

1. Edit any to-do item
2. Press enter
3. Edit the same to-do item again
4. Press Enter

oopsy error alert is shown

Expected Outcome:
The user should be able to edit the same to-do item multiple times.

**Comment by shreyasachdeva123** [comment]
Done
