### ISSUE TITLE
Add additional check on the delete and done fetch api calls

### ISSUE THREAD

**Issue by JatinBehlCarrot** [shreyasachdeva123/to-do-list#2]
Currently, if the `data-url` is missing from the done and the delete button, fetch call does not throw any oopsy error and just executes the fetch call.
Add a check to make sure the `data-url` value is not null / is available / is not empty before trying to make a fetch patch, fetch delete api call.

Expected behaviour:
If the `data-url` value is not present, the webpage should throw the oopsy error with message. "Unexpected Error"

**Comment by shreyasachdeva123** [comment]
Resolved
