### ISSUE TITLE
Handle server response gracefully

### ISSUE THREAD

**Issue by JatinBehlCarrot** [shreyasachdeva123/to-do-list#3]
Make changes to code such as 
https://github.com/shreyasachdeva123/to-do-list/blob/main/list.js#L32
` .then(() => ul.removeChild(e.target.parentElement))`

https://github.com/shreyasachdeva123/to-do-list/blob/main/list.js#L44
` .then(() => { e.target.previousElementSibling.style.textDecoration = "line-through"; })`

and other then (s)

You should check the server response/code is what you expect and then update your webpage.
Also, you can combine sequential then(s) multiple then(s) into a single then.

example: 
```
 .then(response => console.log(response))
 .then(() => { e.target.previousElementSibling.style.textDecoration = "line-through"; })
 .then(() => { e.target.dataset.completed = "true" })
```

**Comment by shreyasachdeva123** [comment]
Done

**Comment by JatinBehlCarrot** [comment]
this need to be done more
