### ISSUE TITLE
Add editing of title for to-do item

### ISSUE THREAD

**Issue by JatinBehlCarrot** [shreyasachdeva123/to-do-list#8]
A user should be able to edit the title of the to-do item as well.

Flow:
A user can double click on the to-do item and sees an edit title mode ( sees the editable text box)
User should be able to update the title of the to-do item
and save it on the back end. If successful, the front-end should display the updated title as well. Else oopsy error

This can be broken down into multi step if needed.

**Comment by shreyasachdeva123** [comment]
It's done but need to review some minor issues with you.

**Comment by shreyasachdeva123** [comment]
Done
