### ISSUE TITLE
Handle server response gracefully  -2 

### ISSUE THREAD

**Issue by JatinBehlCarrot** [shreyasachdeva123/to-do-list#9]
Make changes to code such as
https://github.com/shreyasachdeva123/to-do-list/blob/main/list.js#L32
.then(() => ul.removeChild(e.target.parentElement))

https://github.com/shreyasachdeva123/to-do-list/blob/main/list.js#L44
.then(() => { e.target.previousElementSibling.style.textDecoration = "line-through"; })

and other then (s)

You should check the server response/code is what you expect and then update your webpage.
Also, you can combine sequential then(s) multiple then(s) into a single then.

i.e understand what is the expected response code for each API call and then check for that response code ( 200 / 204 etc) and if the response code is what you expected. Continue with the then operations. Else, throw the error.

**Comment by shreyasachdeva123** [comment]
Done
